version: '3'

services:
  fabrikamfiber.web:
    image: fabrikamfiber.web:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\dekapur\Documents\Fabrikam\FabrikamFiber.Web:C:\inetpub\wwwroot
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\bin/FabrikamFiber.Web.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
